name: Tests & Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    name: Building for Node v${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ matrix.node-version }}

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ./package-lock.json
          key: deps-${{ github.ref_name }}-${{ hashFiles('./package.json') }}
          restore-keys: |
            deps-${{ github.ref_name }}-${{ hashFiles('./package.json') }}
            deps-${{ github.ref_name }}-
            deps-

      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        env:
          NODE_ENV: ci
        run: npm install --progress=false --audit=false

  runTests:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    name: Runnign Tests for Node v${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ./package-lock.json
          key: deps-${{ github.ref_name }}-${{ hashFiles('./package.json') }}
          restore-keys: |
            deps-${{ github.ref_name }}-${{ hashFiles('./package.json') }}
            deps-${{ github.ref_name }}-
            deps-
      - name: Run tests
        run: npm test

  runAudit:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    name: Auditing for Node v${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ./package-lock.json
          key: deps-${{ github.ref_name }}-${{ hashFiles('./package.json') }}
          restore-keys: |
            deps-${{ github.ref_name }}-${{ hashFiles('./package.json') }}
            deps-${{ github.ref_name }}-
            deps-
      - name: Run Audit
        run: npx --yes better-npm-audit audit -p -l high
